### ISSUE TITLE
HTTPS support

### ISSUE THREAD

**Issue by maximzasorin** [antongunov/favicongrabber.com#12]
API must supports HTTPS for use on client side, otherwise request from HTTPS to API will be blocked by browser.

**Comment by antongunov** [comment]
Hm, exactly. I have just installed an SSL certificate. I'll try to update links in docs and make all requests redirect to secure HTTPS access by this weekend.
Now you can use https://favicongrabber.com/api/
Thank you.

**Comment by bjesus** [comment]
@antongunov it looks like the SSL certificate expired 😢

**Comment by antongunov** [comment]
Auto renewing the SSL-certificate was stopped but I fixed it. Thanks for message!

**Comment by bjesus** [comment]
Thank you for fixing it!
