### ISSUE TITLE
Api appears to return links that don't exist on the page

### ISSUE THREAD

**Issue by kaloncheung124** [antongunov/favicongrabber.com#13]
I'm testing with the website: https://www.20minutes.fr/

And the api I'm calling is: http://favicongrabber.com/api/grab/www.20minutes.fr

One of the results it returns is: https://www.20minutes.fr/favicons/android-chrome-96x96.png, but this link doesn't work and it doesn't exist in the source code of their page. Do you know why the api returns this link?

**Comment by antongunov** [comment]
Yes, I know) this link from the manifest file https://assets-v.20mn.fr/manifest.json

```
<link rel="manifest" href="https://assets-v.20mn.fr/manifest.json">
```

**Comment by kaloncheung124** [comment]
Ah I understand now. Thank you for the fast response!
