### ISSUE TITLE
Support other link selectors

### ISSUE THREAD

**Issue by mawarijo** [antongunov/favicongrabber.com#16]
Is it possible to include
- meta itemprop=“image”
- meta property=“og:image”

as link selectors for the images grabbed? I'm trying to grab larger favicons (not just 16x16) but a lot of websites are moving away from including larger sized favicon images in favor of these tags.
Otherwise the api is easy to use and works well, thanks!

**Comment by antongunov** [comment]
Yes, it is possible. I will add support for og:image.
Thank you.

**Comment by mawarijo** [comment]
Sounds great, thanks for the reply and I look forward to testing it out!
